"use client";

import { useCallback, useState } from "react";
import { Cpu, KeyRound, Pencil, Play, Plus, Save, Trash2 } from "lucide-react";
import { request } from "@/lib/api";
import type { Model } from "@/lib/admin";
import { Badge, Button, Card, Modal, Notice, Spinner } from "../ui";
import { Loading, useAction, useResource } from "./shared";

export function ModelsPanel() {
  const resource = useResource<{ items: Model[] }>("/api/admin/models"), action = useAction();
  const [form, setForm] = useState<{ id?: string; name: string; url: string; model: string; api_key: string; enabled: boolean; clear_key: boolean } | null>(null);
  const [deleting, setDeleting] = useState<Model | null>(null);
  const close = useCallback(() => setForm(null), []), closeDelete = useCallback(() => setDeleting(null), []);
  return <><div className="admin-section-head"><div><h2>模型配置</h2><p>OpenAI 兼容接口 · 保存后即时生效 · 本次请求使用固定配置</p></div><Button variant="primary" onClick={() => setForm({ name: "", url: "https://", model: "", api_key: "", enabled: true, clear_key: false })}><Plus size={14} />添加模型</Button></div>{action.feedback}<Loading {...resource} /><div className="admin-model-grid">{resource.data?.items.map(model => <Card className={`admin-model card-pad ${model.active ? "is-active" : ""}`} key={model.id}><div className="card-head"><span className="admin-icon"><Cpu size={19} /></span><Badge tone={model.active ? "green" : "neutral"}>{model.active ? "当前使用" : model.enabled ? "备用" : "已停用"}</Badge></div><h3>{model.name}</h3><p className="admin-model-id">{model.model}</p><div className="admin-model-endpoint">{model.url}</div><div className="admin-model-key"><KeyRound size={12} />{model.has_key ? "密钥已安全保存 · 不可读取" : "未设置密钥 · 适用于无需密钥的本地/内网接口"}</div><div className="admin-model-actions"><Button disabled={action.busy || !model.enabled} onClick={() => action.run(async () => { const value = await request<{ connected: boolean; message: string; seconds?: number }>(`/api/admin/models/${model.id}/test`, { method: "POST" }); if (!value.connected) throw new Error(value.message); }, "接口连接成功")}>{action.busy ? <Spinner /> : <Play size={12} />}测试连接</Button><Button disabled={action.busy || model.active || !model.enabled} onClick={() => action.run(async () => { await request(`/api/admin/models/${model.id}/activate`, { method: "POST" }); resource.reload(); }, "已切换模型，新问题开始使用此配置")}>设为当前</Button><Button variant="ghost" aria-label={`编辑模型 ${model.name}`} onClick={() => setForm({ ...model, api_key: "", enabled: !!model.enabled, clear_key: false })}><Pencil size={13} /></Button><Button variant="ghost" disabled={model.active || action.busy} aria-label={`删除模型 ${model.name}`} onClick={() => setDeleting(model)}><Trash2 size={13} /></Button></div></Card>)}</div>
    {form && <Modal title={form.id ? "编辑模型" : "添加模型配置"} subtitle="密钥留空时保留原值；完整接口示例以 /v1/chat/completions 结尾" onClose={close}><form onSubmit={e => { e.preventDefault(); action.run(async () => { await request(`/api/admin/models${form.id ? "/" + form.id : ""}`, { method: form.id ? "PUT" : "POST", body: JSON.stringify(form) }); setForm(null); resource.reload(); }, "模型配置已保存"); }}><div className="form-grid"><label className="form-field">配置名称<input required maxLength={80} value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} /></label><label className="form-field">模型标识<input required maxLength={200} placeholder="提供商返回的模型 ID" value={form.model} onChange={e => setForm({ ...form, model: e.target.value })} /></label><label className="form-field form-span">完整 API 地址<input type="url" required value={form.url} onChange={e => setForm({ ...form, url: e.target.value })} /></label><label className="form-field form-span">API Key · 不回显<input type="password" autoComplete="new-password" maxLength={4096} value={form.api_key} onChange={e => setForm({ ...form, api_key: e.target.value, clear_key: false })} placeholder={form.id ? "留空保留现有密钥" : "本机无密钥模型可留空"} /></label><label className="admin-toggle"><input type="checkbox" checked={form.enabled} onChange={e => setForm({ ...form, enabled: e.target.checked })} />启用此模型</label>{form.id && <label className="admin-toggle"><input type="checkbox" checked={form.clear_key} onChange={e => setForm({ ...form, clear_key: e.target.checked, api_key: "" })} />清除已保存密钥</label>}</div><Notice>支持 HTTP 与 HTTPS 接口（公网建议 HTTPS），不跟随重定向。连接检测会产生一次小额模型调用；未通过检测的配置也可保存，但请先检测再切换。</Notice>{action.feedback}<div className="modal-actions"><Button onClick={close}>取消</Button><Button type="submit" variant="primary" disabled={action.busy}>{action.busy ? <Spinner /> : <Save size={13} />}保存配置</Button></div></form></Modal>}
    {deleting && <Modal title="删除模型配置？" onClose={closeDelete}><p className="long-description">删除 {deleting.name} 及其已保存密钥，此操作不可恢复。</p><div className="modal-actions"><Button onClick={closeDelete}>取消</Button><Button enterConfirm disabled={action.busy} onClick={() => action.run(async () => { await request(`/api/admin/models/${deleting.id}`, { method: "DELETE" }); setDeleting(null); resource.reload(); }, "已删除模型配置")}><Trash2 size={13} />确认删除</Button></div>{action.feedback}</Modal>}
  </>;
}

